### PR TITLE
Demo file rocks

### PR DESCRIPTION
**Pull request by ericcurtin**
Creating an absolutely brilliant file for y'all

### CODE REVIEW

**Comment by ghost** [comment]
@ericcurtin It sure does

**Comment by ericcurtin** [comment]
Thanks @eoinoconghaile!

**Comment by ghost** [comment]
This file should be flushed down the :toilet:

**Comment by ericcurtin** [comment]
Well I'm gonna merge my own code anyway @eoinoconghaile because I think it's brilliant (hope this doesn't happen on domino)

**Pull request merged**
